

class PaymentServiceError(Exception): ...

class OrderNotFoundError(PaymentServiceError): ...
class PaymentNotFoundError(PaymentServiceError): ...
class OrderAlreadyPaidError(PaymentServiceError): ...
class InsufficientOrderBalanceError(PaymentServiceError): ...
class InvalidPaymentStatusError(PaymentServiceError): ...
class NotAcquiringPaymentError(PaymentServiceError): ...